import React, { useEffect, useRef, useState } from "react";

const QUICK_PROMPTS = [
  "What is an algorithm?",
  "Explain data structures",
  "Tell me about linear algebra",
  "How do I prepare for exams?",
];

function ChatbotPage() {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const endRef = useRef(null);

  const scrollToBottom = () => {
    if (endRef.current) {
      endRef.current.scrollIntoView({ behavior: "smooth" });
    }
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const sendMessage = (text) => {
    if (!text.trim()) return;

    const userMessage = { sender: "user", text };
    const botMessage = {
      sender: "bot",
      text:
        "Demo answer: This is generated by OmniCampus AI. Use a real backend integration for live answers from course content.",
    };

    setMessages((prev) => [...prev, userMessage, botMessage]);
    setInput("");
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    sendMessage(input);
  };

  return (
    <div className="chat-page">
      <header className="chat-header">
        <div className="chat-title">
          <span className="chat-title-avatar">🤖</span>
          <div>
            <h1>OmniCampus AI Chat</h1>
          </div>
        </div>
      </header>

      <main className="chat-main">
        <section className="chat-topbar">
          <div className="chat-prompts">
            {QUICK_PROMPTS.map((prompt) => (
              <button
                key={prompt}
                type="button"
                className="prompt-pill"
                onClick={() => sendMessage(prompt)}
              >
                {prompt}
              </button>
            ))}
          </div>
        </section>

        <section className="chat-window" aria-live="polite">
          <div className="chat-messages">
            {messages.map((msg, index) => (
              <article
                key={`${msg.sender}-${index}`}
                className={`chat-message ${msg.sender}`}
                aria-label={`${msg.sender} message`}
              >
                <div className="message-avatar">{msg.sender === "bot" ? "🤖" : "🧑"}</div>
                <div className="message-bubble">
                  <p>{msg.text}</p>
                </div>
              </article>
            ))}
            <div ref={endRef} />
          </div>
        </section>
      </main>

      <form className="chat-input" onSubmit={handleSubmit}>
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask a question about your course materials..."
          rows={1}
          aria-label="Type your message"
        />
        <button type="submit" className="send-btn">
          Send
        </button>
      </form>
    </div>
  );
}

export default ChatbotPage;